name: flutter_slidable_for_tencent_im
description: A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
version: 1.4.0
homepage: https://github.com/letsar/flutter_slidable_for_tencent_im

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  collection:

flutter:
